export const BUSINESS_CARD_TITLE_KEYWORDS = [
  "manager",
  "general manager",
  "export manager",
  "sales manager",
  "marketing manager",
  "business development manager",
  "purchasing manager",
  "procurement manager",
  "finance manager",
  "accounting manager",
  "regional manager",
  "customer representative",
  "sales & marketing",
  "sales and marketing",
  "sales and marketing specialist",
  "customer relationship manager",
  "investment adviser",
  "investment advisor",
  "deputy general manager",
  "sales director",
  "director",
  "chief",
  "coordinator",
  "koordinatör",
  "koordinator",
  "coordinator",
  "architect",
  "engineer",
  "sales engineer",
  "test engineer",
  "assistant",
  "purchasing",
  "logistics",
  "office manager",
  "area manager",
  "division manager",
  "executive",
  "owner",
  "founder",
  "partner",
  "specialist",
  "consultant",
  "representative",
  "geschäftsführer",
  "vertrieb",
  "vertriebsleiter",
  "verkaufsleiter",
  "einkaufsleiter",
  "abteilungsleiter",
  "sachbearbeiter",
  "außendienst",
  "innendienst",
  "leiter",
  "managerin",
  "leiterin",
  "prokurist",
  "verkauf",
  "müdür",
  "müdürü",
  "genel müdür",
  "genel müdür yardımcısı",
  "genel mudur yardimcisi",
  "satış müdürü",
  "pazarlama müdürü",
  "satış ve pazarlama",
  "satış ve pazarlama sorumlusu",
  "planlama ve satış sorumlusu",
  "planlama ve satis sorumlusu",
  "satış ve pazarlama müdürü",
  "ihracat müdürü",
  "ithalat müdürü",
  "muhasebe müdürü",
  "finans müdürü",
  "iş geliştirme müdürü",
  "müşteri temsilcisi",
  "satış temsilcisi",
  "satis temsilcisi",
  "sales representative",
  "department",
  "bölüm",
  "bolum",
  "bölümü",
  "bolumu",
  "müşteri yöneticisi",
  "is geliştirme yöneticisi",
  "iş geliştirme yöneticisi",
  "şube müdürü",
  "sube muduru",
  "satış yöneticisi",
  "satis yoneticisi",
  "koordinatör",
  "koordinator",
  "depolardan sorumlu",
  "yatırım danışmanı",
  "yatirim danismani",
  "yatırım uzmanı",
  "yatirim uzmani",
  "satın alma müdürü",
  "lojistik müdürü",
  "bölge sorumlusu",
  "uzmanı",
  "uzmani",
  "sorumlu",
  "yönetici",
  "yonetici",
  "meclis üyesi",
  "menajer",
  "менеджер",
  "директор",
  "генеральный директор",
  "коммерческий директор",
  "руководитель",
  "менеджер по продажам",
  "председатель",
  "заместитель директора",
  "руководитель отдела продаж",
  "начальник отдела продаж",
  "специалист",
  "ведущий специалист",
  "инженер",
  "главный инженер",
  "директор по продажам",
  "директор по развитию",
  "менеджер по развитию",
  "руководитель проекта",
] as const;

export const BUSINESS_CARD_COMPANY_MARKERS = [
  "a.ş",
  "aş",
  "anonim şirket",
  "ltd",
  "ltd.",
  "ltd şti",
  "ltd. şti",
  "şti",
  "şti.",
  "limited",
  "limited company",
  "san",
  "tic",
  "san. ve tic.",
  "san. tic.",
  "holding",
  "group",
  "grup",
  "llc",
  "l.l.c",
  "inc",
  "co. ltd",
  "company",
  "corp",
  "corporation",
  "kg co",
  "gmbh",
  "ag",
  "kg",
  "ohg",
  "ug",
  "mbh",
  "s.l",
  "s.a",
  "sh.p.k",
  "ooo",
  "ооо",
  "ip",
  "ип",
  "zao",
  "зао",
  "oao",
  "оао",
  "ao",
  "ао",
  "pao",
  "пао",
] as const;

export const BUSINESS_CARD_INDUSTRY_KEYWORDS = [
  "makine",
  "makina",
  "tekstil",
  "otomasyon",
  "otomasyonu",
  "otomotiv",
  "gıda",
  "ihracat",
  "ithalat",
  "lojistik",
  "plastik",
  "metal",
  "kimya",
  "cam",
  "balkon",
  "hırdavat",
  "inşaat",
  "danışmanlık",
  "danismanlik",
  "hizmetleri",
  "sistemleri",
  "yapi",
  "yapı",
  "univar",
  "ünivar",
  "mobilya",
  "construction",
  "solutions",
  "consultancy",
  "consulting",
  "çözümleri",
  "cozumleri",
  "security",
  "security systems",
  "locks",
  "trade",
  "trading",
  "machine",
  "machinery",
  "metal",
  "bio",
  "biotech",
  "automation",
  "hardware",
  "profile",
  "aksesuarları",
  "aksesuarlari",
  "pvc",
  "otomatik",
  "doğrama",
  "dograma",
  "panjur",
  "kepenk",
  "sürme",
  "surme",
  "küpeşte",
  "kupeste",
  "sineklik",
  "aluminium",
  "alüminyum",
  "maquinaria",
  "vertrieb",
  "handel",
  "industrie",
  "technik",
  "technologie",
  "metall",
  "handel",
  "машиностроение",
  "металл",
  "торговля",
  "био",
  "системс",
  "системы",
  "безопасность",
  "автоматизация",
  "инжиниринг",
  "логистика",
  "промышленность",
] as const;

export const BUSINESS_CARD_ADDRESS_HINTS = [
  "mah",
  "mh",
  "mahalle",
  "cad",
  "cadde",
  "sok",
  "sokak",
  "sk",
  "bulvar",
  "bulv",
  "blv",
  "no",
  "no:",
  "d:",
  "blok",
  "kat",
  "daire",
  "da",
  "apt",
  "plaza",
  "han",
  "merkez",
  "fabrika",
  "sit",
  "site",
  "osb",
  "bölgesi",
  "organize",
  "posta",
  "pk",
  "calle",
  "nave",
  "parque",
  "business park",
  "parku",
  "zona",
  "street",
  "st",
  "road",
  "rd",
  "avenue",
  "ave",
  "blvd",
  "boulevard",
  "suite",
  "ste",
  "unit",
  "floor",
  "building",
  "nr",
  "nr.",
  "hausnummer",
  "straße",
  "strasse",
  "str",
  "platz",
  "weg",
  "gasse",
  "ulitsa",
  "ul",
  "ulica",
  "prospekt",
  "pr-t",
  "pr",
  "dom",
  "stroenie",
  "ofis",
  "office",
  "офис",
  "ул",
  "улица",
  "проспект",
  "дом",
  "стр",
  "д",
  "д.",
  "стр.",
  "пр-т",
  "пр.",
  "шоссе",
  "наб",
  "наб.",
  "пом",
  "пом.",
  "каб",
  "каб.",
  "корп",
  "корп.",
  "обл",
  "обл.",
] as const;

export const BUSINESS_CARD_CONTACT_TOKENS = [
  "e-mail",
  "email",
  "mail",
  "tel",
  "telefon",
  "gsm",
  "mobile",
  "mob",
  "cell",
  "office",
  "fax",
  "faks",
  "тел",
  "тел.",
  "моб",
  "моб.",
  "доб",
  "доб.",
  "почта",
  "e-mail",
  "linkedin",
  "instagram",
  "facebook",
  "twitter",
  "x.com",
] as const;

function normalizeToken(value: string): string {
  return value
    .toLocaleLowerCase("tr-TR")
    .replace(/\./g, "")
    .replace(/\s+/g, " ")
    .trim();
}

export function lineContainsLexiconToken(line: string, dictionary: readonly string[]): boolean {
  const normalizedLine = normalizeToken(line);
  return dictionary.some((token) => {
    const normalizedToken = normalizeToken(token);
    if (!normalizedToken) return false;

    if (normalizedToken.length <= 3 || /^[a-zçğıöşüäöüßа-яё]+$/i.test(normalizedToken)) {
      const escaped = normalizedToken.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const boundaryRegex = new RegExp(`(^|[^\\p{L}\\p{N}])${escaped}($|[^\\p{L}\\p{N}])`, "iu");
      return boundaryRegex.test(normalizedLine);
    }

    return normalizedLine.includes(normalizedToken);
  });
}
