import { StyleSheet } from "react-native";

export const STOCK_BROWSE_CARD_GAP = 6;
export const STOCK_BROWSE_CARD_IMAGE_HEIGHT = 64;

export const stockBrowseStyles = StyleSheet.create({
  cardFrame: {
    width: "100%",
    borderRadius: 10,
    overflow: "visible",
  },
  cardFrameTooltipOpen: {
    zIndex: 30,
    elevation: 30,
  },
  cardPressable: { width: "100%" },
  cardPressed: { opacity: 0.92 },
  cardImage: {
    width: "100%",
    overflow: "hidden",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  cardImageAsset: { width: "100%", height: "100%" },
  cardSelectedBadge: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  cardImageMetaRow: {
    position: "absolute",
    left: 5,
    bottom: 5,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 3,
    zIndex: 10,
    maxWidth: "88%",
  },
  cardBody: {
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 7,
    gap: 3,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  cardCodeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  cardCode: {
    flex: 1,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  cardName: {
    fontSize: 10,
    fontWeight: "500",
    lineHeight: 13,
  },
  cardBodyExtra: {
    fontSize: 10,
    fontWeight: "600",
    lineHeight: 13,
  },
  stockNameWrap: {
    position: "relative",
  },
  stockNameWrapActive: {
    zIndex: 40,
  },
  stockNameTooltip: {
    position: "absolute",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    zIndex: 50,
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  stockNameTooltipAbove: {
    left: -6,
    right: -6,
    bottom: "100%",
    marginBottom: 4,
  },
  stockNameTooltipBelow: {
    left: 0,
    right: 0,
    top: "100%",
    marginTop: 4,
  },
  stockNameTooltipText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 15,
  },
  cardChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 3,
    marginTop: 1,
    minHeight: 18,
  },
  cardChip: {
    maxWidth: "100%",
    borderRadius: 5,
    borderWidth: 1,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  cardChipText: {
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 0.1,
  },
  cardFooter: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  stockUnitBadge: {
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 32,
    alignItems: "center",
  },
  stockUnitBadgeCompact: {
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignItems: "center",
    flexShrink: 0,
  },
  stockUnitBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  stockUnitBadgeCompactText: {
    fontSize: 8,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  listItemShell: { width: "100%", alignSelf: "stretch", overflow: "visible" },
  listItemShellTooltipOpen: {
    zIndex: 30,
    elevation: 30,
  },
  listRowPressable: { width: "100%" },
  listRowInner: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 58,
    gap: 10,
  },
  listRowPressed: { opacity: 0.9 },
  listIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  listTextCol: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    gap: 1,
    overflow: "visible",
  },
  listCode: { fontSize: 10, fontWeight: "700", letterSpacing: 0.15 },
  listName: { fontSize: 11, fontWeight: "500", lineHeight: 14 },
  listActionsCol: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    flexShrink: 0,
    marginLeft: 4,
  },
  listMetaRow: {
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 12,
    paddingBottom: 8,
    paddingTop: 4,
    marginLeft: 50,
  },
  listMetaContent: { gap: 2 },
  listMetaInlineRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  listMetaText: {
    fontSize: 10,
    fontWeight: "600",
    lineHeight: 13,
  },
  stockListShell: {
    borderRadius: 16,
    borderWidth: 1.5,
    overflow: "hidden",
    alignSelf: "stretch",
    flexGrow: 0,
  },
  listContentInset: {
    paddingVertical: 4,
  },
  listSeparator: {
    height: 1,
    marginHorizontal: 12,
  },
  listItemWrap: {
    width: "100%",
    alignSelf: "stretch",
  },
  cardRow: {
    gap: STOCK_BROWSE_CARD_GAP,
    alignItems: "stretch",
  },
  cardCell: {
    marginBottom: STOCK_BROWSE_CARD_GAP,
    alignSelf: "stretch",
  },
});
